spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/feed_db}
spring.datasource.username=${DATABASE_USER:postgres}
spring.datasource.password=${DATABASE_PASS:admin}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

api.security.token.secret=${JWT_SECRET:minha_chave_super_secreta_local_123}

cloudinary.cloud-name=dcctsjkr3
cloudinary.api-key=593883773781945
cloudinary.api-secret=2Sz-86FEVOJSYEinaE_gq2Wi2xs

server.port=${PORT:8080}